### ISSUE TITLE
Making this reusable

### ISSUE THREAD

**Issue by jhermann** [drvinceknight/Talks#1]
Hi, there, I read your blog post, and this seems to be a thing I might use. To be able to improve the mechanism and also use it easily with one's own content, the Python scripts etc. should be split into their own repository and then re-imported through either `git submodule` or `git subtree`. Adding some supporting code (create a virtualenv, import some useful stuff into it) would make this unnoticable after first setup, i.e. you could have something like `talks view` (what `serve.py` does right now), `talks publish`, and so on.

That'd make sharing the infrastructure and forking it for PRs much much easier. ☺

**Comment by drvinceknight** [comment]
Sorry @jhermann , I only just saw this! That's a great idea. I will work on it :)

**Comment by jhermann** [comment]
BTW, infrastructure for a project with a CLI stub and testing and so on…

https://github.com/Springerle/py-generic-project

**Comment by drvinceknight** [comment]
Thanks! I've recently put this together which has given me some (much!) needed experience:

https://github.com/drvinceknight/Axelrod

**Comment by drvinceknight** [comment]
I've just finished putting this together :)

The latest build off this was done using https://github.com/drvinceknight/ghtalks

Not done as a submodule as that package is now on pip. Let me know what you think :)
